Repository TeamChoiKang/antique-universe-front-end, pull requests merged in 2021-08, with the labels that each got.

#48 Feature/change way socket emit
  src/phaser/scene/VillageScene/index.js
Labels: ANTIQUE-UNIVERSE, with서버, 기능추가

#50 Fix/character position emit
  src/phaser/character/cursor/DefaultCursorStrategy.js
Labels: ANTIQUE-UNIVERSE, 기능수정, 논의필요

#51 Feature/create shop
  src/assets/map/shop/shop-map.json
  src/components/PhaserRender/index.js
  src/phaser/scene/ShopScene/index.js
  src/phaser/scene/VillageScene/index.js
  src/phaser/scene/sceneKeys.js
Labels: 기능추가, ANTIQUE-UNIVERSE

#57 [feature] constructor return 으로 변경
  src/phaser/character/Character.js
  src/phaser/character/CharacterFactory.js
Labels: ANTIQUE-UNIVERSE, 리팩토링

#56 Feature/change current character socket event
  src/phaser/scene/VillageScene/index.js
Labels: 기능수정, with서버, ANTIQUE-UNIVERSE

#59 Feature/append another village
  src/assets/tileMap/shop/shop-tile-map.json
  src/assets/tileMap/village/village-tile-map.json
  src/phaser/character/cursor/CursorStrategy.js
  src/phaser/map/MapManager.js
  src/phaser/scene/SceneManager/index.js
  src/phaser/scene/ShopScene/index.js
  src/phaser/scene/VillageScene/index.js
  src/utils/socket/index.js
Labels: 기능추가, with서버, ANTIQUE-UNIVERSE

#61 Feature/signin signin
  .eslintrc.js
  src/App.js
  src/api/AuthService.js
  src/api/HttpClient.js
  src/constants.js
  src/pages/Main/index.js
  src/pages/SignIn/Auth.js
  src/pages/SignIn/AuthFactory.js
  src/pages/SignIn/KaKaoOAuth.js
  src/pages/SignIn/OAuth.js
  src/pages/SignIn/OauthStrategy.js
  src/pages/SignIn/index.js
  src/router/PrivateRoute.js
  src/router/index.js
  src/utils/socket/index.js
Labels: 기능추가, ANTIQUE-UNIVERSE

#62 Feature/signin http method post
  src/api/AuthService.js
  src/api/HttpClient.js
  src/pages/SignIn/index.js
Labels: 기능수정, with서버, ANTIQUE-UNIVERSE

#65 Feature/create gm character
  src/phaser/character/Character.js
  src/phaser/character/CharacterFactory.js
  src/phaser/character/cursor/CursorStrategy.js
  src/phaser/character/cursor/GmCursorStrategy.js
  src/phaser/scene/VillageScene/index.js
Labels: 기능추가

#64 Feature/new tile map
  src/assets/tile-set.png
  src/assets/tileMap/shop/shop-tile-map.json
  src/assets/tileMap/village/village-tile-map.json
  src/phaser/scene/SceneManager/index.js
Labels: 기능추가

#68 Feature/create modal scene
  src/assets/icon/close-icon.png
  src/components/PhaserRender/index.js
  src/phaser/scene/ModalScene/index.js
  src/phaser/scene/SceneManager/index.js
  src/phaser/scene/VillageScene/index.js
Labels: 기능추가, ANTIQUE-UNIVERSE

#66 Feature/signup signup
  .eslintrc.js
  package-lock.json
  package.json
  src/api/AuthService.js
  src/api/HttpClient.js
  src/package/immutable/index.js
  src/pages/SignIn/index.js
  src/pages/SignUp/index.js
  src/pages/SignUp/signup.css
  src/utils/validation/KoreanValidator.js
  src/utils/validation/LengthValidator.js
  src/utils/validation/NumberValidator.js
  src/utils/validation/RequiredValidator.js
  src/utils/validation/Validator.js
  src/utils/validation/ValidatorChainBuilder.js
Labels: 기능추가, with서버, ANTIQUE-UNIVERSE
