Repository TeamChoiKang/antique-universe-front-end, pull requests merged in 2021-07, with the labels that each got.

#21 [refactor] Server socket refactoring 변경 적용
  src/phaser/scene/VillageScene/index.js
Labels: ANTIQUE-UNIVERSE, with서버

#16 [feature] 메인페이지 개발
  package-lock.json
  package.json
  src/assets/antique-universe-logo.png
  src/pages/Main/index.js
  src/pages/Main/main.css
Labels: ANTIQUE-UNIVERSE, 기능추가, 논의필요

#25 [feature] signin page 기초작업
  src/pages/SignIn/index.js
  src/pages/SignIn/signin.css
Labels: ANTIQUE-UNIVERSE, 기능추가

#23 [refactor] map builder 리팩터링 후 적용
  src/phaser/map/MapBuilder.js
  src/phaser/map/MapFactory.js
  src/phaser/map/MapManager.js
  src/phaser/map/builder/DefaultMapBuilder.js
  src/phaser/scene/VillageScene/index.js
Labels: ANTIQUE-UNIVERSE, 리팩토링

#38 Feat/build build setting
  package.json
  src/AppRouter.js
Labels: ANTIQUE-UNIVERSE, 버그수정, 환경설정

#40 Chore/prettier prettier
  .prettierrc.js
  .vscode/settings.json
  jsconfig.json
  src/pages/Game/game.css
Labels: ANTIQUE-UNIVERSE, 버그수정, 환경설정

#36 Feat/tile map
  src/assets/map/village/village-map.json
  src/assets/tile-set.png
  src/phaser/map/MapManager.js
  src/phaser/map/builder/DefaultMapBuilder.js
  src/phaser/scene/VillageScene/index.js
Labels: ANTIQUE-UNIVERSE, 기능수정, 기능추가

#41 Fix/character jump
  src/phaser/character/cursor/DefaultCursorStrategy.js
Labels: ANTIQUE-UNIVERSE, 버그수정

#43 Feat/signin accessToken
  .eslintrc.js
  package-lock.json
  package.json
  src/api/ApiService.js
  src/api/AuthService.js
  src/api/HttpClient.js
  src/constants.js
  src/model/User.js
  src/package/http/index.js
  src/package/queryString/index.js
  src/pages/SignIn/KaKaoOauthStrategy.js
  src/pages/SignIn/OauthStrategy.js
  src/pages/SignIn/index.js
Labels: ANTIQUE-UNIVERSE, 기능추가, 논의필요

#47 Refactoring/socket
  src/phaser/scene/VillageScene/index.js
  src/utils/socket/index.js
Labels: ANTIQUE-UNIVERSE, 리팩토링

#49 Feat/setting hotfix
  .eslintrc.js
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  .vscode/settings.json
  src/AppRouter.js
  src/constants.js
Labels: ANTIQUE-UNIVERSE, 핫픽스, 환경설정
